name: DevSecOps-Final-Run
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Scan Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'aniketpuro/solar-system:latest'
          format: 'table'
          exit-code: '0' # Abhi ke liye 0 rakhte hain taaki pipeline pass ho jaye aur hum ArgoCD dekh sakein
          severity: 'CRITICAL,HIGH'

      - name: Final Push
        run: |
          docker build -t aniketpuro/solar-system:latest .
          docker push aniketpuro/solar-system:latest